apiVersion: v1
kind: ReplicationController
metadata:
  namespace: ezia-parking-mvp-dev
  name: redis
spec:
  replicas: 3
  selector:
    name: redis
  template:
    metadata:
      labels:
        name: redis
        role: master
    spec:
      containers:
      - name: redis
        image: 192.168.1.166:9443/library/redis-cluster:0.1
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "1024Mi"
            cpu: "0.1"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
        - name: data