apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis
    redis-sentinel: "true"
    role: master
  name: redis-master
  namespace: ezia-parking-mvp-dev
spec:
  containers:
    - name: master
      image: 192.168.1.166:9443/library/redis-cluster:0.1
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      resources:
        limits:
          memory: "1024Mi"
          cpu: "0.1"
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
    - name: sentinel
      image: 192.168.1.166:9443/library/redis-cluster:0.1
      resources:
        limits:
          memory: "1024Mi"
          cpu: "0.1"
      env:
        - name: SENTINEL
          value: "true"
      ports:
        - containerPort: 26379
  volumes:
    - name: data
      emptyDir: {}